# Generated by Django 4.0.5 on 2022-06-19 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('msg', models.TextField(max_length=600)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
